/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface DecentragramInterface extends ethers.utils.Interface {
  functions: {
    "imageCount()": FunctionFragment;
    "images(uint256)": FunctionFragment;
    "name()": FunctionFragment;
    "tipImageOwner(uint256)": FunctionFragment;
    "uploadImage(string,string)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "imageCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "images",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "tipImageOwner",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "uploadImage",
    values: [string, string]
  ): string;

  decodeFunctionResult(functionFragment: "imageCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "images", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "tipImageOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uploadImage",
    data: BytesLike
  ): Result;

  events: {
    "ImageCreated(uint256,string,string,uint256,address)": EventFragment;
    "ImageTipped(uint256,string,string,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "ImageCreated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ImageTipped"): EventFragment;
}

export type ImageCreatedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, string] & {
    id: BigNumber;
    hash: string;
    description: string;
    tipAmount: BigNumber;
    author: string;
  }
>;

export type ImageTippedEvent = TypedEvent<
  [BigNumber, string, string, BigNumber, string] & {
    id: BigNumber;
    hash: string;
    description: string;
    tipAmount: BigNumber;
    author: string;
  }
>;

export class Decentragram extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DecentragramInterface;

  functions: {
    imageCount(overrides?: CallOverrides): Promise<[BigNumber]>;

    images(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string] & {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;

    name(overrides?: CallOverrides): Promise<[string]>;

    tipImageOwner(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uploadImage(
      _imgHash: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  imageCount(overrides?: CallOverrides): Promise<BigNumber>;

  images(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string, BigNumber, string] & {
      id: BigNumber;
      hash: string;
      description: string;
      tipAmount: BigNumber;
      author: string;
    }
  >;

  name(overrides?: CallOverrides): Promise<string>;

  tipImageOwner(
    _id: BigNumberish,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uploadImage(
    _imgHash: string,
    _description: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    imageCount(overrides?: CallOverrides): Promise<BigNumber>;

    images(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string, BigNumber, string] & {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;

    name(overrides?: CallOverrides): Promise<string>;

    tipImageOwner(_id: BigNumberish, overrides?: CallOverrides): Promise<void>;

    uploadImage(
      _imgHash: string,
      _description: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "ImageCreated(uint256,string,string,uint256,address)"(
      id?: null,
      hash?: null,
      description?: null,
      tipAmount?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, string],
      {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;

    ImageCreated(
      id?: null,
      hash?: null,
      description?: null,
      tipAmount?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, string],
      {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;

    "ImageTipped(uint256,string,string,uint256,address)"(
      id?: null,
      hash?: null,
      description?: null,
      tipAmount?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, string],
      {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;

    ImageTipped(
      id?: null,
      hash?: null,
      description?: null,
      tipAmount?: null,
      author?: null
    ): TypedEventFilter<
      [BigNumber, string, string, BigNumber, string],
      {
        id: BigNumber;
        hash: string;
        description: string;
        tipAmount: BigNumber;
        author: string;
      }
    >;
  };

  estimateGas: {
    imageCount(overrides?: CallOverrides): Promise<BigNumber>;

    images(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    name(overrides?: CallOverrides): Promise<BigNumber>;

    tipImageOwner(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uploadImage(
      _imgHash: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    imageCount(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    images(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    tipImageOwner(
      _id: BigNumberish,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uploadImage(
      _imgHash: string,
      _description: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
