/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Decentragram } from "./Decentragram";

export { Decentragram__factory } from "./factories/Decentragram__factory";
